// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240425165316_Seed")]
    partial class Seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.PlatformUser", b =>
                {
                    b.Property<int>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfileId"));

                    b.Property<string>("CreationDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FollowerCount")
                        .HasColumnType("int");

                    b.Property<int>("FollowingCount")
                        .HasColumnType("int");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlatformUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProfileId");

                    b.ToTable("PlatformUsers");

                    b.HasData(
                        new
                        {
                            ProfileId = 1,
                            CreationDate = "2022-01-01",
                            Description = "Description1",
                            FollowerCount = 100,
                            FollowingCount = 50,
                            Platform = "Twitter",
                            PlatformUsername = "User1"
                        },
                        new
                        {
                            ProfileId = 2,
                            CreationDate = "2022-02-01",
                            Description = "Description2",
                            FollowerCount = 200,
                            FollowingCount = 100,
                            Platform = "Facebook",
                            PlatformUsername = "User2"
                        },
                        new
                        {
                            ProfileId = 3,
                            CreationDate = "2022-03-01",
                            Description = "Description3",
                            FollowerCount = 300,
                            FollowingCount = 150,
                            Platform = "Instagram",
                            PlatformUsername = "User3"
                        },
                        new
                        {
                            ProfileId = 4,
                            CreationDate = "2022-04-01",
                            Description = "Description4",
                            FollowerCount = 400,
                            FollowingCount = 200,
                            Platform = "YouTube",
                            PlatformUsername = "User4"
                        },
                        new
                        {
                            ProfileId = 5,
                            CreationDate = "2022-05-01",
                            Description = "Description5",
                            FollowerCount = 500,
                            FollowingCount = 250,
                            Platform = "LinkedIn",
                            PlatformUsername = "User5"
                        });
                });

            modelBuilder.Entity("WebApplication1.Posts", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CommentsCount")
                        .HasColumnType("int");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LikesCount")
                        .HasColumnType("int");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.HasKey("PostId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            Caption = "First Post",
                            CommentsCount = 5,
                            Date = "2022-01-02",
                            LikesCount = 10,
                            ProfileId = 1
                        },
                        new
                        {
                            PostId = 2,
                            Caption = "Second Post",
                            CommentsCount = 6,
                            Date = "2022-01-03",
                            LikesCount = 12,
                            ProfileId = 1
                        },
                        new
                        {
                            PostId = 3,
                            Caption = "Hello World",
                            CommentsCount = 8,
                            Date = "2022-02-02",
                            LikesCount = 15,
                            ProfileId = 2
                        },
                        new
                        {
                            PostId = 4,
                            Caption = "Another Post",
                            CommentsCount = 2,
                            Date = "2022-03-03",
                            LikesCount = 5,
                            ProfileId = 3
                        },
                        new
                        {
                            PostId = 5,
                            Caption = "Second Post User 2",
                            CommentsCount = 4,
                            Date = "2022-02-05",
                            LikesCount = 8,
                            ProfileId = 2
                        },
                        new
                        {
                            PostId = 6,
                            Caption = "Post Three User 3",
                            CommentsCount = 7,
                            Date = "2022-03-06",
                            LikesCount = 9,
                            ProfileId = 3
                        },
                        new
                        {
                            PostId = 7,
                            Caption = "YouTube First Post",
                            CommentsCount = 12,
                            Date = "2022-04-07",
                            LikesCount = 30,
                            ProfileId = 4
                        },
                        new
                        {
                            PostId = 8,
                            Caption = "LinkedIn Intro",
                            CommentsCount = 10,
                            Date = "2022-05-08",
                            LikesCount = 20,
                            ProfileId = 5
                        });
                });

            modelBuilder.Entity("WebApplication1.Videos", b =>
                {
                    b.Property<int>("VideoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VideoId"));

                    b.Property<int>("CommentsCount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LikesCount")
                        .HasColumnType("int");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UploadDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VideoId");

                    b.ToTable("Videos");

                    b.HasData(
                        new
                        {
                            VideoId = 1,
                            CommentsCount = 10,
                            Description = "Welcome to my channel",
                            LikesCount = 20,
                            ProfileId = 4,
                            Title = "Introduction Video",
                            UploadDate = "2022-04-02"
                        },
                        new
                        {
                            VideoId = 2,
                            CommentsCount = 12,
                            Description = "Learn something new",
                            LikesCount = 30,
                            ProfileId = 5,
                            Title = "Tutorial Video",
                            UploadDate = "2022-05-02"
                        },
                        new
                        {
                            VideoId = 3,
                            CommentsCount = 11,
                            Description = "First Insta Video",
                            LikesCount = 25,
                            ProfileId = 3,
                            Title = "InstaVid 1",
                            UploadDate = "2022-03-05"
                        },
                        new
                        {
                            VideoId = 4,
                            CommentsCount = 3,
                            Description = "What's happening",
                            LikesCount = 5,
                            ProfileId = 1,
                            Title = "TwitterVid 1",
                            UploadDate = "2022-01-07"
                        },
                        new
                        {
                            VideoId = 5,
                            CommentsCount = 9,
                            Description = "Live session on Facebook",
                            LikesCount = 18,
                            ProfileId = 2,
                            Title = "Facebook Live",
                            UploadDate = "2022-02-07"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
